#!/bin/bash

search_engine_file="${W3M_CONFIG_HOME}/search-engines.yaml"
unset url_sub
declare -a extra_options

while [[ $# -gt 0 ]]; do
	case "$1" in
		-U)
			url_sub="$2"
			shift
			;;
		--option|-o)
			extra_options+=("$2")
			shift
			;;
		*) break ;;
	esac
	shift
done

if [[ $# -lt 1 ]]; then
	cat << _EOF_
w3m-control: BACK
w3m-control: MESSAGE Please provide at least one search engine name

_EOF_
	exit 0
fi

if [[ ${url_sub} ]]; then
	search_engine_str="$(sed -e "s#${url_sub}#%s#g" <<< "${W3M_URL}")"
else
	form="${W3M_CURRENT_FORM}"

	if [[ ! ${form} ]]; then
		cat << _EOF_
w3m-control: BACK
w3m-control: MESSAGE Cursor must be over search form field

_EOF_
		exit 0
	fi

	form="$(sed -e "s#!CURRENT_URL!#${W3M_URL}#g" <<< "${form}")"
	search_engine_str="$(sed -re 's#.*name="([0-9A-Za-z\._-]+)" \([A-Z]+ ([0-9A-Za-z\.:/_?-]+)\).*#\2?\1=%s#' <<< "${form}")"
	if [[ "${search_engine_str[*]::1}" = '/' ]]; then
		search_engine_str="$(grep -o -e 'https*://[^/]*' <<< "$W3M_URL")${search_engine_str}"
	fi
	for opt in ${extra_options[*]}; do
		search_engine_str="${search_engine_str}&${opt}"
	done
fi

# combine search engine names into comma-separated list
search_engine_names="$1"
shift
for name; do
	search_engine_names="${search_engine_names}, ${name}"
done

echo "${search_engine_names}: ${search_engine_str}" >> "${search_engine_file}"

num_search_engines="$(wc -l < "${search_engine_file}")"

cat << _EOF_
w3m-control: BACK
w3m-control: MESSAGE Added search engine ${search_engine_str} as ${search_engine_names} (#${num_search_engines})

_EOF_
