#!/bin/bash

function print_help() {
	cat << _EOF_
HTTP/2
Content-Type: text/plain; charset=utf-8

Usage: $(basename $0) [OPTIONS ...] files ...

Options:
	--command, -C:		edit commands in \$W3M_CONFIG_HOME/cmd; initialize script if new file
	--executable, -E:	edit commands in \$W3M_CONFIG_HOME/bin; initialize script if new file
	--cgi, -G:			edit commands in \$W3M_CONFIG_HOME/cgi-bin; initialize script if new file
	--help, -h:			display help (this file)
_EOF_
}
# end function print_help

root_dir="${W3M_CONFIG_HOME}"
[[ ! ${EDITOR} ]] && EDITOR=vim

while [[ $# -gt 0 ]]; do
	case "$1" in
		--tmux|-t)
			W3M_USE_TMUX=t
			;;
		--no-tmux|-nt)
			W3M_USE_TMUX=f
			;;
		--command|-C)
			should_init=t
			root_dir="${W3M_CONFIG_HOME}/cmd"
			;;
		--executable|-E)
			should_init=t
			root_dir="${W3M_CONFIG_HOME}/bin"
			;;
		--cgi|-G)
			should_init=t
			root_dir="${W3M_CONFIG_HOME}/cgi-bin"
			;;
		--help|-h)
			print_help
			exit 0
			;;
		*) break ;;
	esac
	shift
done

if [[ ! $1 ]]; then
	cat << _EOF_
w3m-control: BACK
w3m-control: MESSAGE ERROR: at least one file required

_EOF_
	exit 0
fi

declare -a files
for fname; do
	fname_full="${root_dir}/${fname}"
	if [[ "${should_init}" = t && ! -f "${fname_full}" ]]; then
		cat > "${fname_full}" << _EOF_
#!/bin/bash

_EOF_
		chmod 777 "${fname_full}"
	fi
	files+=("${fname_full}")
done

if [[ "${W3M_USE_TMUX}" = t ]]; then
	cat << _EOF_
w3m-control: BACK
w3m-control: EXTERN tmux-launch new-window "${EDITOR} ${files[*]}"; echo %s >/dev/null

_EOF_
else
	cat << _EOF_
w3m-control: BACK
w3m-control: SHELL ${EDITOR} ${files[*]}

_EOF_
fi
