#!/bin/bash

use_preset=t

while [[ $# -gt 0 ]]; do
	case "$1" in
		--url|-u)
			extern_cmd='EXTERN'
			;;
		--link|-l)
			extern_target='EXTERN_LINK'
			;;
		--image|-i)
			extern_target='EXTERN_LINK'
			;;
		# NOTE: now the default
		--preset|-p)
			use_preset=t
			;;
		--unique|-u)
			use_preset=f
			;;
		*) break ;;
	esac
	shift
done

[[ ! ${extern_cmd} ]] && case "$(basename $0)" in
	extern_link|el)
		extern_cmd='EXTERN_LINK'
		;;
	extern_image|extern_img|ei)
		extern_cmd='EXTERN_LINK'
		;;
	*)
		extern_cmd='EXTERN'
		;;
esac

if [[ ${use_preset} = t ]]; then
	preset_name="$1"
	[[ ! ${preset_name} ]] && echo "no preset external provider named" >&2 && exit 1
	preset_file="${W3M_CONFIG_HOME}/external-browsers.yaml"
	preset_idx=1
	IFS=$'\n\r' preset_data=($(grep -v '^#' < ${preset_file}))
	for line in ${preset_data[*]}; do
		IFS=':' read key val <<< "${line}"
		val="$(grep -o '\S.*\S' <<< "${val}")"
		if [[ ${preset_idx} = ${preset_name} ]]; then
			preset_found=t
		else
			IFS=', ' keys=(${key})
			for k in $(IFS=', '; echo ${keys[*]}); do
				[[ "$k" = "${preset_name}" ]] && preset_found=t && break
			done
		fi
		[[ ${preset_found} = t ]] && shell_cmd="${val}" && break
		let 'preset_idx += 1'
	done
	[[ ! ${shell_cmd} ]] && echo "could not find preset for \"${preset_name}\" in ${preset_file}" >&2 && exit 1
else
	shell_cmd="$1"
fi

cat << _EOF_
w3m-control: BACK
w3m-control: ${extern_cmd} ${shell_cmd}

_EOF_

