#!/bin/bash

# Executes a program in your $PATH and displays the output.
# Unlike READ_SHELL, displays both stdout and stderr, and output can be interpreted as different mime-types.
# If aliased to another name using a symlink, the program by that name will be executed.
# 
# Usage: exec [OPTIONS ...] PROGRAM_NAME [PROGRAM_ARGS ...]
#
# Options:
# 	--content-type, -T MIME_TYPE			Sets Content-Type header to MIME_TYPE, so command output will be interpreted as such
# 	--pipe-source, -S						Pipe source file ($W3M_SOURCEFILE) to program
# 	--pipe-buffer, -B						Pipe current buffer to program. This is done by opening the source file in another instance of w3mp using w3mp -dump

# defaults
content_type='text/plain'

while [[ $# -gt 0 ]]; do
	case "$1" in
		--content-type|-T)
			content_type="$2"
			shift
			;;
		--pipe-source|-S)
			src_cmd="cat ${W3M_SOURCEFILE}"
			;;
		--pipe-buffer|-B)
			src_cmd="w3mp -dump ${W3M_SOURCEFILE}"
			;;
		*) break ;;
	esac
	shift
done

bname="$(basename $0)"

case "${bname}" in
	exec|x)
		unset prog_name
		;;
	*)
		prog_name="${bname}"
		;;
esac

cat << _EOF_
HTTP/1.1 200 OK
Content-Type: ${content_type}

$(if [[ ${src_cmd} ]]; then
	eval "${src_cmd}" | eval "${prog_name} $*" 2>&1
else
	eval "${prog_name} $*" 2>&1
fi)
_EOF_

