#!/bin/bash

goto_cmd='GOTO'

while [[ $# -gt 0 ]]; do
	case "$1" in
		--link|-l)
			use_link=t
			;;
		--tab|-t)
			goto_cmd='TAB_GOTO'
			;;
		*) break ;;
	esac
	shift
done

if [[ ${use_link} ]]; then
	url="${W3M_CURRENT_LINK}"
elif [[ $1 ]]; then
	url="$1"
else
	url="${W3M_URL}"
fi

cat << _EOF_
w3m-control: BACK
w3m-control: ${goto_cmd} firefox://${url}

_EOF_
