#!/bin/bash

[[ ! ${W3M_CMD_PATH} ]] && W3M_CMD_PATH="${W3M_CONFIG_HOME}/cmd"

IFS=: read -a cmd_dirs <<< "${W3M_CMD_PATH}"

cat << _EOF_
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8

Available Commands:

_EOF_

for dir in ${cmd_dirs[*]}; do
	if test -d "${dir}"; then
		for file in "${dir}"/*; do
			if test -x "${file}"; then
				if test -h "${file}"; then
					echo "$(basename "${file}") -> $(readlink "${file}")"
				else
					basename "${file}"
				fi
			fi
		done
	fi
done

