#!/bin/bash

# Three selection settings:
# 1. thread (--thread, -t): select an arbitrary thread
# 2. subreddit (--subreddit, -r): select an arbitrary subreddit
# 3. user (--user, -u): select an arbitrary user
# 4. current url (.): select subreddit or user from current url
# 5. current link (,): select subreddit or user from current link

function thread_mode() {
	thread_id="$1"; sorter="$2"
	[[ ! ${thread_id} ]] && exit 2
	echo 'w3m-control: BACK'
	if [[ ! ${sorter} ]]; then
		echo "w3m-control: GOTO_RELATIVE https://${prefix}.reddit.com/${thread_id}/${suffix}"
	else
		echo "w3m-control: GOTO_RELATIVE https://${prefix}.reddit.com/${thread_id}/${suffix}?sort=${sorter}"
	fi
	echo ''
	exit 0
}
# end function thread_mode

function subreddit_mode() {
	subreddit="$1"; sorter="$2"; time_period="$3"
	[[ ! ${subreddit} ]] && exit 2
	echo 'w3m-control: BACK'
	if [[ ! ${sorter} ]]; then
		echo "w3m-control: GOTO_RELATIVE https://${prefix}.reddit.com/r/${subreddit}/${suffix}"
	else
		[[ ! ${time_period} ]] && time_period='day'
		echo "w3m-control: GOTO_RELATIVE https://${prefix}.reddit.com/r/${subreddit}/${sorter}/${suffix}?sort=${sorter}&t=${time_period}"
	fi
	echo ''
	exit 0
}
# end subreddit_mode()

function user_mode() {
	reddit_user="$1"
	[[ ! ${reddit_user} ]] && exit 2
	shift
	case "$1" in
		-*)
			case "$1" in
				--submitted|-s)
					reddit_user_mode='submitted'
					;;
				--overview|-o)
					reddit_user_mode='overview'
					;;
				--comments|-c)
					reddit_user_mode='comments'
					;;
				--gilded|-g)
					reddit_user_mode='gilded'
					;;
				*)
					echo "unrecognized user mode \"$1\"" >&2
					exit 1
					;;
			esac
			shift
			;;
	esac
	sorter="$1"; time_period="$2"
	if [[ ${reddit_user_mode} && "${reddit_user_mode}" != 'overview' ]]; then
		base_url="${reddit_user}/${reddit_user_mode}"
	else
		base_url="${reddit_user}"
	fi
	echo 'w3m-control: BACK'
	if [[ ! ${sorter} ]]; then
		echo "w3m-control: GOTO_RELATIVE https://${prefix}.reddit.com/user/${base_url}/${suffix}"
	else
		[[ ! ${time_period} ]] && time_period='day'
		echo "w3m-control: GOTO_RELATIVE https://${prefix}.reddit.com/user/${base_url}/${suffix}?sort=${sorter}&t=${time_period}"
	fi
	echo ''
	exit 0
}
# end user_mode()

function ambiguous_mode() {
	url="$1"
	shift
	IFS='/' url_path=($(grep -m 1 -o 'reddit\.com/[^?#]\+' <<< "${url}" | sed -e 's#reddit\.com/##'))
	[[ ! ${url_path[1]} ]] && echo "could not parse subreddit or user from url \"${url}\"" >&2 && exit 1
	case "${url_path[0]}" in
		r)
			if [[ "${url_path[2]}" = 'comments' ]]; then
				thread_mode "${url_path[*]}" $*
			else
				subreddit_mode "${url_path[1]}" $*
			fi
			;;
		user|u)
			user_mode "${url_path[1]}" $*
			;;
		*)
			echo "could not parse subreddit or user from url \"${url}\"" >&2
			exit 1
			;;
	esac
	return
}
# end ambiguous_mode

function url_mode() {
	ambiguous_mode "${W3M_URL}" $*
	return
}
# end url_mode

function link_mode() {
	ambiguous_mode "${W3M_CURRENT_LINK}" $*
	return
}
# end link_mode

function help_mode() {
	cmd_name="$(basename $0)"
cat << _EOF_
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8

Usage of ${cmd_name}:

thread mode:
	${cmd_name} --thread|-t THREAD_ID [SORT_TYPE]

subreddit mode:
	${cmd_name} --subreddit|-r SUBREDDIT_NAME [SORT_TYPE [TIME_PERIOD]]

user mode:
	${cmd_name} --user|-u USER_NAME [--submitted/-s|--overview/-o|--comments/-c|--gilded/-g] [SORT_TYPE [TIME_PERIOD]]

url mode:
	${cmd_name} . [SUBREDDIT_MODE_ARGS ... | USER_MODE_ARGS ...]

link mode:
	${cmd_name} , [SUBREDDIT_MODE_ARGS ... | USER_MODE_ARGS ...]
_EOF_
	exit 0
}

# client logic starts here
if [[ "$(basename $0)" = 'ord' || "$(basename $0)" = 'old-reddit' ]]; then
	prefix='old'
	suffix=''
else
	prefix='www'
	suffix='.mobile'
fi
mode="$1"
shift
case "${mode}" in
	--subreddit|-r)
		subreddit_mode $*
		;;
	--user|-u)
		user_mode $*
		;;
	.)
		url_mode $*
		;;
	,)
		link_mode $*
		;;
	--help|-h)
		help_mode $*
		;;
	*)
		to_print_usage=t
		exit 1
		;;
esac

if [[ $? = 2 || ${to_print_usage} = t ]]; then
	echo "usage: $(basename $0) mode MODE_SPECIFIC ARGS ..." >&2
	echo $'\t'"see $(basename $0) --help to see help for mode specific args" >&2
	exit 1
elif [[ $? = 1 ]]; then
	exit 1
fi

