#!/bin/bash

# Choose a user agent from $W3M_CONFIG_HOME/user-agents.txt, or list user agents

case "$1" in
	--list|-l)
		action='list'
		;;
	--add|-a)
		action='add'
		;;
esac

user_agents_file="${W3M_CONFIG_HOME}/user-agents.txt"

if [[ -f "${user_agents_file}" ]]; then
	IFS=$'\n\r' user_agents=($(cat "${user_agents_file}"))
else
	user_agents=('Lynx/2.8.9rel.1 libwww-FM/2.14 SSL-MM/1.4.1 OpenSSL/1.1.1d')
fi

if [[ "${action}" = 'list' ]]; then
	if [[ ${W3M_USER_AGENT} && $(grep -m 1 -o '[0-9]\+' <<< "${W3M_USER_AGENT}") = "${W3M_USER_AGENT}" && "${W3M_USER_AGENT}" -le ${#user_agents[*]} ]]; then
		let 'W3M_USER_AGENT -= 1'
		user_agents[${W3M_USER_AGENT}]="<strong>* ${user_agents[${W3M_USER_AGENT}]}</strong>"
	fi
cat << _EOF_
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta lang="en" />
	<title>Available user agents in ${user_agents_file}</title>
</head>
<body>
<h1>Available user agents in ${user_agents_file}:</h1>

<ol>$(sed -re 's#(.*)#<li>\1</li>#' <<< "${user_agents[*]}")</ol>
</body>
</html>
_EOF_
exit 0
fi

if [[ "${action}" = 'add' ]]; then
	(IFS=$'\n'; echo "${*:2}" >> "${user_agents_file}")
cat << _EOF_
w3m-control: BACK

_EOF_
	exit 0
fi

if [[ $1 ]]; then
	let "index = $1 - 1"
	if [[ "${index}" -lt 0 ]] || [[ "${index}" -ge "${#user_agents[*]}" ]]; then
cat << _EOF_
w3m-control: BACK
w3m-control: MESSAGE ERROR: index out of bounds (got ${index}, ${#user_agents[*]} user agents available)

_EOF_
		exit 0
	fi

	user_agent="${user_agents[${index}]}"

	let 'index += 1'

cat << _EOF_
w3m-control: BACK
w3m-control: SETENV W3M_USER_AGENT=${index}
w3m-control: SET_OPTION user_agent=${user_agent}

_EOF_
else
user_agent="${user_agents[${W3M_USER_AGENT} - 1]}"
cat << _EOF_
w3m-control: BACK
w3m-control: MESSAGE ${user_agent}

_EOF_
fi

